# Generated by Django 5.2.1 on 2025-05-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(max_length=100, unique=True)),
                ('fhir_resource', models.JSONField()),
                ('observation_date', models.DateTimeField()),
                ('code', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_observations', to='patients.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_observations', to='patients.patient')),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='FHIRPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(max_length=100, unique=True)),
                ('fhir_resource', models.JSONField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_data', to='patients.patient')),
            ],
        ),
    ]
